# Generated by Django 2.2.7 on 2019-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptioni',
            new_name='description',
        ),
    ]
